name: "Validate Build"
on: [push, pull_request]

jobs:
  validation:
    name: "Validation"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: gradle/wrapper-validation-action@v1

      - name: Gradle Build Action
        uses: gradle/gradle-build-action@v2.7.1

      - name: Execute Gradle build
        run: ./gradlew build
